{% set data = load_setup_py_data() %}

package:
  name: palladium
  version: {{ data.get('version') }}

source:
  path: ..

build:
  script_env:
   - CONDA_BLD_PATH
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    - pld-admin = palladium.fit:admin_cmd
    - pld-devserver = palladium.server:devserver_cmd
    - pld-fit = palladium.fit:fit_cmd
    - pld-grid-search = palladium.fit:grid_search_cmd
    - pld-list = palladium.eval:list_cmd
    - pld-stream = palladium.server:stream_cmd
    - pld-test = palladium.eval:test_cmd
    - pld-upgrade = palladium.util:upgrade_cmd
    - pld-version = palladium.util:version_cmd

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docopt
    - flask
    - joblib
    - numpy
    - pandas
    - psutil
    - scikit-learn
    - sqlalchemy
    - ujson
    - requests
    - requests-mock
    - pytest
    - pytest-cov

  run:
    - python
    - setuptools
    - docopt
    - flask
    - joblib
    - numpy
    - pandas
    - psutil
    - scikit-learn
    - sqlalchemy
    - ujson
    - requests

test:
  # Python imports
  imports:
    - palladium
    # - palladium.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - py.test --pyargs palladium
    - pld-admin --help
    - pld-devserver --help
    - pld-fit --help
    - pld-grid-search --help
    - pld-list --help
    - pld-stream --help
    - pld-test --help
    - pld-upgrade --help
    - pld-version --help
      
# You can also put a file called run_test.py in the recipe that will be run
# at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose
    - pytest
    - pytest-cov
    - requests-mock

about:
  home: https://github.com/ottogroup/palladium
  license: Apache Software License
  summary: 'Framework for setting up predictive analytics services'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
